RESIZE_IMAGE:
  WIDTH: 1200
EDGE_DETECTION:
  LOW_THRESHOLD: 90
  HIGH_THRESHOLD: 400
  APERTURE: 3
LINE_DETECTION:
  THRESHOLD: 100
  DIAGONAL_LINE_ELIMINATION: true
  DIAGONAL_LINE_ELIMINATION_THRESHOLD_DEGREES: 30
RANSAC:
  OFFSET_TOLERANCE: .15
  BEST_SOLUTION_TOLERANCE: .1
MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE: .5
BORDER_REFINEMENT:
  LINE_WIDTH: 4
  WARPED_SQUARE_SIZE: [50, 50]
  NUM_SURROUNDING_SQUARES_IN_WARPED_IMG: 5
  SOBEL_KERNEL_SIZE: 3
  EDGE_DETECTION:
    APERTURE: 3
    HIGH_THRESHOLD: 300
    LOW_THRESHOLD: 120
