_BASE_: config://occupancy_classifier/_base.yaml

TRAINING:
  PHASES:
    - EPOCHS: 1
      OPTIMIZER:
        LEARNING_RATE: 0.001
        NAME: Adam
      PARAMS: head
    - EPOCHS: 2
      OPTIMIZER:
        LEARNING_RATE: 0.0001
        NAME: Adam
      PARAMS: all
