_BASE_: config://_classifier_base.yaml

DATASET:
  PATH: data://pieces
  CLASSES:
    - black_bishop
    - black_king
    - black_knight
    - black_pawn
    - black_queen
    - black_rook
    - white_bishop
    - white_king
    - white_knight
    - white_pawn
    - white_queen
    - white_rook
  BATCH_SIZE: 16
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE: [100, 200]
    RANDOM_HORIZONTAL_FLIP: null

TRAINING:
  PHASES:
    - EPOCHS: 6
      OPTIMIZER:
        LEARNING_RATE: 0.001
        NAME: Adam
      PARAMS: all
