DATASET:
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE:
    - 299
    - 299
TRAINING:
  MODEL:
    NAME: InceptionV3
    REGISTRY: PIECE_CLASSIFIER
_BASE_: config://piece_classifier/_base_pretrained.yaml
